# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:/Myapp/sc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(233, 303)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Mj_Sazeh Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: lightblue;")
        self.label.setObjectName("label")
        self.lineEdit_name = QtWidgets.QLineEdit(Form)
        
        self.lineEdit_name.setGeometry(QtCore.QRect(10, 70, 131, 31))
        self.lineEdit_name.setStyleSheet("background-color: lightblue;")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_lastna = QtWidgets.QLineEdit(Form)
        self.lineEdit_lastna.setGeometry(QtCore.QRect(10, 120, 131, 31))
        self.lineEdit_lastna.setStyleSheet("background-color: lightblue;")
        self.lineEdit_lastna.setObjectName("lineEdit_lastna")
        self.lineEdit_telephon = QtWidgets.QLineEdit(Form)
        self.lineEdit_telephon.setGeometry(QtCore.QRect(10, 170, 131, 31))
        self.lineEdit_telephon.setStyleSheet("background-color: lightblue;")
        self.lineEdit_telephon.setObjectName("lineEdit_telephon")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 70, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: white;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(150, 110, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: white;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(150, 170, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:white;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(160, 220, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: white;")
        self.label_5.setObjectName("label_5")
        self.lineEdit_email = QtWidgets.QLineEdit(Form)
        self.lineEdit_email.setGeometry(QtCore.QRect(10, 220, 131, 31))
        self.lineEdit_email.setStyleSheet("background-color: lightblue;")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.pushButton_Register = QtWidgets.QPushButton(Form)
        self.pushButton_Register.setGeometry(QtCore.QRect(70, 260, 101, 41))
        font = QtGui.QFont()
        font.setFamily("B Koodak")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Register.setFont(font)
        self.pushButton_Register.clicked.connect(self.savefale)
        self.pushButton_Register.setStyleSheet("background-color: white;")
        self.pushButton_Register.setObjectName("pushButton_Register")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "فرم ثبت نام"))
        self.label_2.setText(_translate("Form", "نام"))
        self.label_3.setText(_translate("Form", "نام خانوادگی"))
        self.label_4.setText(_translate("Form", "شماره تلفن"))
        self.label_5.setText(_translate("Form", "ایمیل"))
        self.pushButton_Register.setText(_translate("Form", "ثبت نام"))

    def savefale(self,a):
     g=list()

     a = str(self.lineEdit_name.text())
     b = str(self.lineEdit_lastna.text())
     c = str(self.lineEdit_email.text())
     d   = str(self.lineEdit_name.text())

     g.append("name:")
     g.append(a)
     g.append("lastname:")
     g.append(b)
     g.append("email:")
     g.append(c)
     g.append("telephone:")
     g.append(d)
     print(a,b,c,d)

     file = open("savefile", "w")
     file.write(str(g))
     file.close()

      
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
